version: '3.0'

volumes:
    postgres-data:

networks:
    yasd:

services:
    postgres:
        build:
            context: postgres/
            dockerfile: Dockerfile
        container_name: postgres
        shm_size: 2G
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/yasd'
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -h postgres -U ${POSTGRES_USER}"]
          interval: 30s
          timeout: 30s
          retries: 1000
        command: postgres
        volumes:
           - postgres-data:/var/lib/postgresql
        restart: unless-stopped
        ports:
          - "5444:5432"
        networks:
            - yasd

    # pgadmin:
    #     image: dpage/pgadmin4
    #     depends_on:
    #         - postgres
    #     ports:
    #         - "53603:53603"
    #         - "80:80"
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@example.com
    #         PGADMIN_DEFAULT_PASSWORD: root
    #     networks:
    #         - yasd
