version: '3.0'

volumes: 
    postgres-data:



networks:
    yasd: 

services:
    postgres:
        image: kartoza/postgis:latest
        container_name: postgres 
        shm_size: 2G
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/yasd'
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -h postgres -U ${POSTGRES_USER}"]
          interval: 30s
          timeout: 30s
          retries: 1000
        command: postgres
        volumes:
           - postgres-data:/var/lib/postgresql
        restart: unless-stopped
        ports:
          - "5444:5432"
        networks:
            - yasd
